### ISSUE TITLE
Implementation of Class Balancing

### ISSUE THREAD

**Issue by komms** [Sayan98/pytorch-segnet#2]
Did you implement the **median class balancing technique** as said in the paper?

**Comment by say4n** [comment]
No, mean was used. It is trivial to edit it in. You may create a PR too. :)
The function definition corresponding to the class probabilities can be found [here](https://github.com/Sayan98/pytorch-segnet/blob/4ecd30a7ea8d91389651a1daa807ad926e80051b/src/dataset.py#L56) and [here](https://github.com/Sayan98/pytorch-segnet/blob/4ecd30a7ea8d91389651a1daa807ad926e80051b/src/dataset.py#L71).
