### ISSUE TITLE
Starting loss is too high.

### ISSUE THREAD

**Issue by farhadinima75** [Sayan98/pytorch-segnet#7]
hi say4n.

tnx for your nice and simple implementation.

I've encountered a simple issue in the first epoch loss.

starting loss is high (nearly 150) for me.

is it ok?
does this happen for you when testing your algorithm?

any answer would be appreciated.

**Comment by say4n** [comment]
Hi @farhadinima75 thank you for the kind words, however, I no longer have access to the lab where I worked on this. So, I cannot look up your query. 👍
